'use client';
import {useState,useEffect} from 'react';
export default function Home(){
 const [projects,setProjects]=useState<any[]>([]); const [active,setActive]=useState(''); const [msgs,setMsgs]=useState<any>({}); const [input,setInput]=useState('');
 useEffect(()=>{setProjects(JSON.parse(localStorage.getItem('p')||'[]')); setMsgs(JSON.parse(localStorage.getItem('m')||'{}'))},[]);
 useEffect(()=>{localStorage.setItem('p',JSON.stringify(projects))},[projects]); useEffect(()=>{localStorage.setItem('m',JSON.stringify(msgs))},[msgs]);
 const send=async()=>{if(!input.trim()||!active)return; const nm=[...(msgs[active]||[]),{role:'user',content:input}]; setMsgs({...msgs,[active]:nm}); setInput(''); try{const r=await fetch('/api/agent',{method:'POST',body:JSON.stringify({user_message:input})}); const d=await r.json(); setMsgs({...msgs,[active]:[...nm,{role:'assistant',content:d.reply}]})}catch(e:any){setMsgs({...msgs,[active]:[...nm,{role:'assistant',content:'Error '+e.message}]})}};
 return(<div style={{display:'flex',flexDirection:'column',height:'100vh'}}><header style={{padding:12,borderBottom:'1px solid #222',display:'flex',justifyContent:'space-between'}}><b>[build me]</b><button onClick={()=>{const n=prompt('Project name?'); if(n){const id=Date.now().toString(); setProjects([...projects,{id,name:n}]); setMsgs({...msgs,[id]:[]}); setActive(id)}}} style={{background:'#8b5cf6',border:0,padding:'6px 12px',borderRadius:8,color:'white'}}>+ New</button></header><div style={{display:'flex',gap:8,padding:8,overflowX:'auto',borderBottom:'1px solid #222'}}>{projects.map((p:any)=><button key={p.id} onClick={()=>setActive(p.id)} style={{padding:'6px 12px',borderRadius:20,border:'1px solid #333',background:active===p.id?'#8b5cf6':'#18181b',color:'white'}}>{p.name}</button>)}</div><div style={{flex:1,overflowY:'auto',padding:12,display:'flex',flexDirection:'column',gap:10}}>{(msgs[active]||[]).map((m:any,i:number)=><div key={i} style={{alignSelf:m.role==='user'?'flex-end':'flex-start',maxWidth:'85%',background:m.role==='user'?'#8b5cf6':'#18181b',padding:'10px 12px',borderRadius:12,whiteSpace:'pre-wrap',fontSize:14}}>{m.content}</div>)}</div><div style={{padding:10,borderTop:'1px solid #222',display:'flex',gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Describe game idea..." style={{flex:1,padding:12,borderRadius:12,border:'1px solid #333',background:'#18181b',color:'white'}}/><button onClick={send} style={{background:'#8b5cf6',border:0,padding:'0 18px',borderRadius:12,color:'white'}}>↑</button></div></div>)
                                                                                                                                                               }
